title: ğŸ‘©ğŸ½â€ğŸ’» Nazik Ali Abdelrahman
logo: assets/img/photo_2025-06-03_15-32-28.jpg
description: ğŸŒŸElectrical and Electronics Engineering| Renewable Energy | Artificial Intellegence | Data Analytics| Project management| Problem-Solving.
#show_downloads: true
theme: jekyll-theme-minimal
