title: ğŸ‘©ğŸ½â€ğŸ’» Nazik Ali Abdelrahman
logo: assets/img/photo_2025-06-03_15-32-28.jpg
description: ğŸŒŸ Electrical and Electronics Engineer| Renewable Energy | Artificial Intellegence | Data Analytic|Project management| Problem-Solving.
#show_downloads: true
theme: jekyll-theme-minimal
