title: ğŸ‘©ğŸ½â€ğŸ’» Nazik Ali Abdelrahman
logo: assets/img/photo_2025-06-03_15-32-28.jpg
description: Electrical and Electronics Engineer| Renewable Energy | Artificial Intellegence in Engineering| Data Analytics in Engineering
#show_downloads: true
theme: jekyll-theme-minimal
